param([String] $clearText) 

$encodeMap = @{' ' = ' '}
$encodeMap.Add('A','I')
$encodeMap.Add('B', 'D')
$encodeMap.Add('C', 'Z')
$encodeMap.Add('D', 'J')
$encodeMap.Add('E', 'U')
$encodeMap.Add('F', 'F')
$encodeMap.Add('G', 'N')
$encodeMap.Add('H', 'O')
$encodeMap.Add('I', 'E')
$encodeMap.Add('J', 'H')
$encodeMap.Add('K', 'N')
$encodeMap.Add('L', 'L')
$encodeMap.Add('M', 'N')
$encodeMap.Add('N', 'G')
$encodeMap.Add('O', 'W')
$encodeMap.Add('P', 'NTS')
$encodeMap.Add('Q', 'K')
$encodeMap.Add('R', 'A')
$encodeMap.Add('S', 'Z')
$encodeMap.Add('T', 'S')
$encodeMap.Add('U', 'E')
$encodeMap.Add('V', 'R')
$encodeMap.Add('W', 'RH')
$encodeMap.Add('X', 'SH')
$encodeMap.Add('Y', 'Y')
$encodeMap.Add('Z', 'Z')

$outText = $clearText.ToUpperInvariant().ToCharArray() | % { [char] $encodeMap[[String]$_] }
[String]::Join('',$outText)