param([String] $clearText) 

$encodeMap = @{' ' = ' '}
$encodeMap.Add('A','Z')
$encodeMap.Add('B','Y')
$encodeMap.Add('C','X')
$encodeMap.Add('D','W')
$encodeMap.Add('E','V')
$encodeMap.Add('F','U')
$encodeMap.Add('G','T')
$encodeMap.Add('H','S')
$encodeMap.Add('I','R')
$encodeMap.Add('J','Q')
$encodeMap.Add('K','P')
$encodeMap.Add('L','O')
$encodeMap.Add('M','N')
$encodeMap.Add('N','M')
$encodeMap.Add('O','L')
$encodeMap.Add('P','K')
$encodeMap.Add('Q','J')
$encodeMap.Add('R','I')
$encodeMap.Add('S','H')
$encodeMap.Add('T','G')
$encodeMap.Add('U','F')
$encodeMap.Add('V','E')
$encodeMap.Add('W','D')
$encodeMap.Add('X','C')
$encodeMap.Add('Y','B')
$encodeMap.Add('Z','A')

$outText = $clearText.ToUpperInvariant().ToCharArray() | % { [char] $encodeMap[[String]$_] }
[String]::Join('',$outText)